#!/bin/bash

verbose=false
port=""

# Parse command-line options
while getopts ":vp:" opt; do
  case $opt in
    v)
      verbose=true
      ;;
    p)
      port=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [[ -n $port ]]; then
  if $verbose; then
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./jbod_server_binary -v -p "$port"
  else
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:." ./jbod_server_binary -p "$port"
  fi
else
  echo "No port provided."
fi
